# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180725_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_image/<django.db.models.query_utils.DeferredAttribute object at 0x05AA7070>'),
        ),
    ]
